<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Hutschienenmoped_XL" Comment="Subapplication Type" >
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DO" Type="Hutschienenmoped_XL_8_DO" x="1246.67" y="13.33">
			<Parameter Name="QI" Value="TRUE"/>
			<Parameter Name="u8SAMember" Value="isobus::GLOBAL"/>
			<Parameter Name="u16ObjId" Value="isobus::ID_NULL"/>
			<Parameter Name="DigitalOutput_Q1" Value="'App.Control.functions.Schneidwerk.rechtslauf'"/>
			<Parameter Name="DigitalOutput_Q2" Value="'App.Control.functions.Vorsteuerventil_2A.QX'"/>
			<Parameter Name="DigitalOutput_Q3" Value="'App.Control.functions.Vorsteuerventil_2B.QX'"/>
			<Parameter Name="DigitalOutput_Q4" Value="'App.Control.functions.Klappen.Sitzventile.QXA'"/>
			<Parameter Name="DigitalOutput_Q5" Value="'App.Control.functions.Klappen.Sitzventile.QXB'"/>
			<Parameter Name="DigitalOutput_Q6" Value="'App.Control.functions.Verteiler.Sitzventile.QXA'"/>
			<Parameter Name="DigitalOutput_Q7" Value="'App.Control.functions.Verteiler.Sitzventile.QXB'"/>
			<Parameter Name="DigitalOutput_Q8" Value="'App.Control.functions.Licht.QX'"/>
		</FB>
	</SubAppNetwork>
</SubAppType>
