<?xml version="1.0" encoding="UTF-8"?>
<SubAppType Name="mapping_Hutschienenmoped_XL" Comment="Subapplication Type">
	<Identification Standard="61499-2">
	</Identification>
	<VersionInfo Version="1.0" Author="Franz" Date="2023-01-29">
	</VersionInfo>
	<SubAppInterfaceList>
		<SubAppEventInputs>
			<SubAppEvent Name="INIT" Type="Event" Comment="">
			</SubAppEvent>
		</SubAppEventInputs>
	</SubAppInterfaceList>
	<SubAppNetwork>
		<FB Name="Hutschienenmoped_XL_8_DO" Type="Hutschienenmoped_XL_8_DO" Comment="" x="1246.6666666666667" y="13.333333333333334">
			<Parameter Name="QI" Value="TRUE" Comment=""/>
			<Parameter Name="u8SAMember" Value="224" Comment=""/>
			<Parameter Name="u16ObjId" Value="65535" Comment=""/>
			<Parameter Name="DigitalOutput_Q1" Value="'Ventilsteuerung.functions.Schneidwerk.rechtslauf'" Comment=""/>
			<Parameter Name="DigitalOutput_Q2" Value="'Ventilsteuerung.functions.Vorsteuerventil_2A.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q3" Value="'Ventilsteuerung.functions.Vorsteuerventil_2B.QX'" Comment=""/>
			<Parameter Name="DigitalOutput_Q4" Value="'Ventilsteuerung.functions.Klappen.Sitzventile.QXA'" Comment=""/>
			<Parameter Name="DigitalOutput_Q5" Value="'Ventilsteuerung.functions.Klappen.Sitzventile.QXB'" Comment=""/>
			<Parameter Name="DigitalOutput_Q6" Value="'Ventilsteuerung.functions.Verteiler.Sitzventile.QXA'" Comment=""/>
			<Parameter Name="DigitalOutput_Q7" Value="'Ventilsteuerung.functions.Verteiler.Sitzventile.QXB'" Comment=""/>
			<Parameter Name="DigitalOutput_Q8" Value="'Ventilsteuerung.functions.Licht.QX'" Comment=""/>
		</FB>
		<EventConnections>
			<Connection Source="INIT" Destination="Hutschienenmoped_XL_8_DO.INIT" Comment="" dx1="640.0" dx2="640.0" dy="0.0">
				<Attribute Name="Visible" Value="false"/>
			</Connection>
		</EventConnections>
	</SubAppNetwork>
</SubAppType>
